### ISSUE TITLE
Problematic install and unreproducible sample

### ISSUE THREAD

**Issue by ansontwk** [apple/ml-simplefold#7]
Thank you for your work in SimpleFold. Very insightful work.

I am currently having issues getting simplefold to work on both MacOS 15.7 and Ubuntu 20.04 stemming from package clashes.

It would very helpful if you could update with more information regarding the environments and installation process.

1. Incompatibility of toml files using editable pip install

The install instructions calls for installing dependencies using pip in editable mode. This seems to not be compatible with the provided toml file, throwing error that setup.py not being present. 

This problem can be largely remedied by removing the -e flag

2. Missing esm in install process
The sample notebook calls the wrapper package which in turn calls esm_network. This seems to import esm, but esm is not included in the install process.

It would be very helpful to provide the esm version in the readme. Installation of esm using pip install esm throws an Attribute error where 'esm' has no attribute 'data'

3. Python version clarification needed

The toml file calls for mlx==0.28, which seems integral to the pipeline. However pip (version 25.2) could not resolve this version. Changing the version to 0.26.3 seems to resolve this.

This links to the arbitrary python versioning. Biotite==1.2.0 requires python 3.10 or above, yet the installation process nor readme provide information which python version is recommended.

Updating the readme with more information would be helpful.

**Comment by mbautistamartin** [comment]
@yuyangw has made a couple of fixes including updating the README. Please try again with the new instructions in the README and let us know if you hit any issues.
